version: '3.8'

networks: 
  internal:
    driver: bridge
    name: internal

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: dotnet-mongodb
      MONGO_INITDB_ROOT_HOST: localhost
      MONGO_INITDB_ROOT_PORT: 27017
      MONGO_INITDB_ROOT_AUTH_SOURCE: admin
    networks:
      - internal

  postgres:
    image: postgres
    container_name: postgres
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres@123
      POSTGRES_DB: postgresdb
    ports:
      - 5432:5432
    networks:
      - internal

  dotnet-mongo:
    image: vitormoschetta/dotnet-mongo
    container_name: dotnet-mongo-api
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5010:5000
    depends_on:
      - mongodb
      - postgres
    environment:
      - DATABASE=mongo
    networks:
      - internal

  dotnet-postgres:
    image: vitormoschetta/dotnet-postgres
    container_name: dotnet-postgres-api
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5020:5000
    depends_on:
      - mongodb
      - postgres
    environment:
      - DATABASE=postgres
    networks:
      - internal
